export const DECREASE_LIST_ITEM_VALUE = 'DECREASE_LIST_ITEM_VALUE';
export const SET_LIST_ITEM_VALUE = 'SET_LIST_ITEM_VALUE';
export const SET_LIST_ITEM_COLOR = 'SET_LIST_ITEM_COLOR';
export const SET_LIST_STATUS = 'SET_LIST_STATUS';

export const ADD_SELECTED_ITEM = 'ADD_SELECTED_ITEM';
export const REMOVE_SELECTED_ITEM = 'REMOVE_SELECTED_ITEM';
export const ADD_WHOLE_LIST = 'ADD_WHOLE_LIST';
export const REMOVE_WHOLE_LIST = 'REMOVE_WHOLE_LIST';
